<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/bestseller.css')?>" />
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
	<?php $helper = $this->helper('bestseller'); ?>
    <div class="page-title">
        <h2><?php echo $helper->getTitle();?></h2>
    </div>
    <?php $_collectionSize = count($_products->getItems()) ?>
    
    <div class="bestseller-grid">   
    <ul>
    <?php $i=1; foreach ($_products->getItems() as $_product): ?>
        <?php if ($i%1!==0): ?>
        <li>
        <?php endif ?>
            <li <?php if($i%3==0 or $i==$_collectionSize){echo 'class="last"';} ?>>           
                <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(122, 109); ?>" width="122" height="109" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                </a>
                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>                
                	<?php if($helper->getratingHide()==0):?>             
						<?php 
                        $storeId    = Mage::app()->getStore()->getId();
                        $summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_product->getEntityId());
                        ?>
                        <?php if($summaryData->getRatingSummary()): ?>                
                            <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>">
                                </div>
                            </div>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if($helper->getpriceHide()==0):?>
                    	<?php echo $this->getPriceHtml($_product, true) ?>
                    <?php endif;?>
                    
                    <?php if($helper->getcartHide()==0):?>
						<?php if($_product->isSaleable()): ?>
                            <button class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><span><?php echo $this->__('Add to Cart') ?></span></span></span></button>
                            <div class="clear"></div>
                        <?php else: ?>
                            <p class="availability"><span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
                            <div class="clear"></div>
                        <?php endif; ?>
                    <?php endif;?>
                    <ul class="add-to-links" style="list-style:none; padding-left:0px;">
                        <?php if($helper->getwishlistHide()==0):?>
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a class="link-wishlist" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($helper->getcompareHide()==0):?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li class="link-compare last"><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        <?php endif; ?>
                    </ul>
                    <?php if($_product->getevent_date()) {echo $_product->getevent_date();} ?>              
        </li>
        <?php if ($i%3==0 or $i==$_collectionSize): ?>
       </li>
        <?php endif ?>
      <?php $i++; endforeach; $kol = $_collectionSize; ?>
    </ul>
    </div>
<?php endif; ?>